### ISSUE TITLE
LagMonitor hint

### ISSUE THREAD

**Issue by xXSchrandXx** [kubotan/Bungeen#2]
Hi,

LagMonitor does give me a hint for your plugin:

`[Server thread/WARN]: [LagMonitor] Plugin Bungeen is performing a blocking action on the main thread. This could be a performance hit Socket: socket://localhost:25594. Such actions should be handled async from the main thread. Report it to the plugin author
[Server thread/WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developer to find the source of the threading action. LagMonitor doesn't prevent this action. It just warns you
java.lang.IllegalAccessException: null
	at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:55) [LagMonitor.jar:?]
	at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:42) [LagMonitor.jar:?]
	at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:27) [LagMonitor.jar:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) [?:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) [?:1.8.0_144]
	at java.net.Socket.connect(Socket.java:538) [?:1.8.0_144]
	at java.net.Socket.<init>(Socket.java:434) [?:1.8.0_144]
	at java.net.Socket.<init>(Socket.java:211) [?:1.8.0_144]
	at space.gorogoro.bungeen.SignUpdater.setSignTextOfPlayers17(SignUpdater.java:194) [Bungeen.jar:?]
	at space.gorogoro.bungeen.SignUpdater.run(SignUpdater.java:107) [Bungeen.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

**Comment by kubotan** [comment]
It was fixed in version 2.0.
Therefore, this issue closed.
