### ISSUE TITLE
When I click on the sign, there comes only: Connecting ... and nothing happens.

### ISSUE THREAD

**Issue by kubotan** [kubotan/Bungeen#5]
The plugin is great but I have a problem: When I click on the sign, there comes only: Connecting ... and nothing happens.

Console during reload:

```
>[2K [09:32:54 INFO]: java.lang.NullPointerException 
at space.gorogoro.bungeen.SignUpdater.run(SignUpdater.java:89) 
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) 
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) 
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) 
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) 
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) 
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) 
at java.lang.Thread.run(Thread.java:748)
```

**Comment by kubotan** [comment]
bugfix
